# SPDX-FileCopyrightText: 2024 Menix-OS Team <info@menix-os.org>
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version = 1

[[annotations]]
path = "**"
SPDX-FileCoprightText = "2024 Menix-OS Team <info@menix-os.org>"
SPDX-License-Identifier = "LGPL-2.1-or-later"
