# SPDX-FileCopyrightText: Menix-OS Team <info@menix-os.org>
# SPDX-License-Identifier: LGPL-2.1-or-later
name: Labeler
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
